version: '3'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80" # Nginx serve ที่พอร์ต 80 ของ container
    depends_on:
      - backend
    networks:
      - app-network
    command: ["pnpm", "dev"]  # เพิ่มคำสั่งนี้ถ้ายังไม่มี


  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000" # Mapping port 5000 บน host กับ container
    networks:
      - app-network
    command: ["pnpm", "dev"]  # เพิ่มคำสั่งนี้ถ้ายังไม่มี

networks:
  app-network:
    driver: bridge
